version: '3.1'

services:

    elasticsearch:
        image: elasticsearch
        volumes:
          - ./elasticsearch/config:/usr/share/elasticsearch/config
          - ./docker/es/data:/data
        environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m" 
        ports:
          - "9200:9200"
          - "9300:9300"

    elasticsearch-plug-head:
        image: mobz/elasticsearch-head:5-alpine
        ports:
          - "9100:9100"
        depends_on:
          - elasticsearch
    kibana:
        image: kibana
        volumes:
          - ./kibana/config/:/usr/share/kibana/config
        ports:
          - 5601:5601
        depends_on:
          - elasticsearch
